### ISSUE TITLE
Code availability

### ISSUE THREAD

**Issue by AOE-khkhan** [nv-tlabs/DefTet#1]
Hi, I am just wondering approximately when the code may be available.

**Comment by SteveJunGao** [comment]
We are still actively working on cleaning the code, it will be released in 1~2 months.

**Comment by AOE-khkhan** [comment]
Great. Thank you

**Comment by AOE-khkhan** [comment]
Any update regarding the code?

**Comment by AOE-khkhan** [comment]
I am just wondering about the update? Thanks.

**Comment by Separius** [comment]
Any updates on this?

**Comment by Runsong123** [comment]
+1 ~
Any updates on this?

**Comment by SteveJunGao** [comment]
Sorry for the late, we have released the code, please check it!
