### ISSUE TITLE
No module named 'utils.lib'

### ISSUE THREAD

**Issue by pinjiang** [nv-tlabs/DefTet#6]
**Running python train_multigpu.py .... indicate error:**

Traceback (most recent call last):
  File "train_multigpu.py", line 10, in <module>
    from layers.DefTet.deftet import DefTet
  File "/home/jiangpin/DefTet/layers/DefTet/deftet.py", line 12, in <module>
    from utils import tet_utils
  File "/home/jiangpin/DefTet/utils/tet_utils.py", line 15, in <module>
    from utils.lib.tet_point_adj.interface import Tet_point_adj
ModuleNotFoundError: No module named 'utils.lib'

**No dependent libs found when installation** :

HOME_DIR="$PWD"
cd "$HOME_DIR/utils/lib/tet_adj_share"
bash do_all.sh
cd "$HOME_DIR/utils/lib/tet_face_adj"
bash do_all.sh
cd "$HOME_DIR/utils/lib/tet_point_adj"
bash do_all.sh
cd "$HOME_DIR/utils/lib/colaps_v"
bash do_all.sh
cd $HOME_DIR

**Comment by SteveJunGao** [comment]
I just uploaded the required files for this, thanks for checking our code!
